<?xml version="1.0"?>
<robot name="robot_rci" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- ========================================== -->
  <!-- Paramètres géométriques du robot -->
  <!-- ========================================== -->
  <xacro:property name="a" value="1.85"/>
  <xacro:property name="b" value="0.35"/>
  <xacro:property name="base_height" value="0.2"/>
  <xacro:property name="base_radius" value="0.15"/>
  <xacro:property name="link_radius" value="0.05"/>
  
  <!-- ========================================== -->
  <!-- Définition des couleurs -->
  <!-- ========================================== -->
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1"/>
  </material>
  
  <material name="red">
    <color rgba="0.8 0.2 0.2 1"/>
  </material>
  
  <material name="green">
    <color rgba="0.2 0.8 0.2 1"/>
  </material>
  
  <material name="grey">
    <color rgba="0.5 0.5 0.5 1"/>
  </material>
  
  <material name="yellow">
    <color rgba="1.0 0.9 0.0 1"/>
  </material>
  
  <material name="orange">
    <color rgba="1.0 0.5 0.0 1"/>
  </material>

  <!-- ========================================== -->
  <!-- Base du robot -->
  <!-- ========================================== -->
  <link name="world"/>
  
  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}"/>
      </geometry>
      <material name="grey"/>
    </visual>
  </link>

  <joint name="world_to_base" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- ========================================== -->
  <!-- Joint 1 : Rotation autour de Z -->
  <!-- ========================================== -->
  <joint name="joint1" type="revolute">
    <parent link="base_link"/>
    <child link="link1_vertical_pole"/>
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-110*pi/180}" upper="${110*pi/180}" effort="50.0" velocity="2.0"/>
  </joint>

  <link name="link1_vertical_pole">
    <!-- Barre verticale - ROUGE -->
    <visual>
      <origin xyz="0 0 0.15" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${link_radius}" length="0.3"/>
      </geometry>
      <material name="red"/>
    </visual>
    
    <!-- Sphère au sommet de la barre verticale -->
    <visual>
      <origin xyz="0 0 0.3" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.07"/>
      </geometry>
      <material name="orange"/>
    </visual>
    
    <!-- Barre horizontale qui part de la base - BLEU -->
    <visual>
      <origin xyz="0 ${-a/2} 0.3" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${link_radius}" length="${a}"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <!-- ========================================== -->
  <!-- Joint 2 : Rotation autour de X -->
  <!-- ========================================== -->
  <joint name="joint2" type="revolute">
    <parent link="link1_vertical_pole"/>
    <child link="link2_pivot"/>
    <origin xyz="0 ${-a} 0.3" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
    <limit lower="0" upper="${80*pi/180}" effort="50.0" velocity="2.0"/>
  </joint>

  <link name="link2_pivot">
    <!-- Sphère au point de pivot -->
    <visual>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <geometry>
        <sphere radius="0.06"/>
      </geometry>
      <material name="yellow"/>
    </visual>
  </link>

  <!-- ========================================== -->
  <!-- Joint 3 : Rotation autour de Z -->
  <!-- ========================================== -->
  <joint name="joint3" type="revolute">
    <parent link="link2_pivot"/>
    <child link="link3"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0" upper="${2*pi}" effort="20.0" velocity="3.0"/>
  </joint>

  <link name="link3">
    <!-- Barre verte fixe -->
    <visual>
      <origin xyz="0 0 ${b/2}" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${link_radius*0.8}" length="${b}"/>
      </geometry>
      <material name="green"/>
    </visual>
  </link>

  <!-- ========================================== -->
  <!-- Joint 4 : Translation le long de Z -->
  <!-- ========================================== -->
  <joint name="joint4" type="prismatic">
    <parent link="link3"/>
    <child link="link4"/>
    <origin xyz="0 0 ${b}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0" upper="0.15" effort="30.0" velocity="0.5"/>
  </joint>

  <link name="link4">
    <!-- Barre télescopique qui se déplace - ORANGE -->
    <visual>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="${link_radius*0.6}" length="0.1"/>
      </geometry>
      <material name="orange"/>
    </visual>
  </link>

  <!-- ========================================== -->
  <!-- Effecteur final (collé à link4) -->
  <!-- ========================================== -->
  <joint name="joint4_to_ee" type="fixed">
    <parent link="link4"/>
    <child link="end_effector"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
  </joint>

  <link name="end_effector">
    <!-- Sphère rouge à l'extrémité -->
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.04"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>

</robot>
